name: CI

on:
  push:
    paths:
      - "model/notebooks/**"
      - "model/src/**"
  pull_request:
    paths:
      - "model/notebooks/**"
      - "model/src/**"

jobs:
  notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install nbstripout nbqa ruff

      - name: Check notebooks have no outputs
        run: |
          nbstripout --verify model/notebooks/*.ipynb

      - name: Lint notebooks and Python scripts
        run: |
          # Lint notebooks
          nbqa ruff model/notebooks/ --select E,F,W --ignore E501
          
          # Lint Python files in src
          ruff model/src/*.py --select E,F,W --ignore E501